#!/usr/bin/env bash
# envelope-build.sh — reference SDK helper.
# Build a v2.0 ECL envelope JSON from an artifact + a contract.
#
# Required flags:
#   --artifact PATH       Payload file to wrap.
#   --contract PATH       Contract YAML for this edge.
#   --performative STR    One of REQUEST|INFORM|PROPOSE|CRITIQUE|DECIDE|DELEGATE|ACKNOWLEDGE|ESCALATE|RESUME|REFUSE.
#   --objective STR       One-sentence goal (<=240 chars).
#
# Optional flags:
#   --message-id UUID
#   --thread-id UUID      Defaults to a fresh UUID; the first envelope of a
#                         thread typically uses the same value as --message-id.
#   --parent-id UUID|null Defaults to null.
#   --from-version SEM    SemVer of the sending Eidolon. Default: '0.0.0'.
#   --to-version SEM      SemVer of the receiver. Default: '0.0.0'.
#   --kind STR            artifact.kind. Default: contract.artifacts[0].kind.
#   --summary STR         context_delta.summary. Default: a placeholder.
#   --tokens-used N       Default: 0.
#   --token-budget N      Default: contract.context_delta.token_budget_max,
#                         or 4000 if the contract is silent.
#   --confidence FLOAT    Default: 0.5.
#   --trust-level STR     low|standard|high. Default: from contract.
#   --host STR            Default: $ECL_HOST or 'raw'.
#   --model STR           Default: $ECL_MODEL or 'unknown'.
#   --tier STR            standard|trance. Default: 'standard'.
#   --integrity-method M  sha256|hmac-sha256. Default: sha256.
#                         hmac-sha256 requires $ECL_HMAC_KEY in env.
#   --ise JSON            Optional ISE trust-hierarchy block (ECL v2.0 §6.5).
#                         Must be a valid JSON object with at minimum
#                         {"assertion_grade":"<grade>"}. When absent, the
#                         ise field is omitted (ISE is optional at v2.0).
#                         Example: --ise '{"assertion_grade":"self-attested"}'
#
# Output: envelope JSON on stdout.
# Exit codes: 0 on success; 1 on bad usage; 2 on integrity computation failure.

set -u

ARTIFACT=""
CONTRACT=""
PERFORMATIVE=""
OBJECTIVE=""
MESSAGE_ID=""
THREAD_ID=""
PARENT_ID="null"
FROM_VERSION="0.0.0"
TO_VERSION="0.0.0"
KIND=""
SUMMARY="(generated by envelope-build.sh; populate before sending)"
TOKENS_USED="0"
TOKEN_BUDGET=""
CONFIDENCE="0.5"
TRUST_LEVEL=""
HOST="${ECL_HOST:-raw}"
MODEL="${ECL_MODEL:-unknown}"
TIER="standard"
INTEGRITY_METHOD="sha256"
ISE_JSON=""

usage() {
  sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
}

while [ $# -gt 0 ]; do
  case "$1" in
    --artifact)            ARTIFACT="$2"; shift 2 ;;
    --contract)            CONTRACT="$2"; shift 2 ;;
    --performative)        PERFORMATIVE="$2"; shift 2 ;;
    --objective)           OBJECTIVE="$2"; shift 2 ;;
    --message-id)          MESSAGE_ID="$2"; shift 2 ;;
    --thread-id)           THREAD_ID="$2"; shift 2 ;;
    --parent-id)           PARENT_ID="$2"; shift 2 ;;
    --from-version)        FROM_VERSION="$2"; shift 2 ;;
    --to-version)          TO_VERSION="$2"; shift 2 ;;
    --kind)                KIND="$2"; shift 2 ;;
    --summary)             SUMMARY="$2"; shift 2 ;;
    --tokens-used)         TOKENS_USED="$2"; shift 2 ;;
    --token-budget)        TOKEN_BUDGET="$2"; shift 2 ;;
    --confidence)          CONFIDENCE="$2"; shift 2 ;;
    --trust-level)         TRUST_LEVEL="$2"; shift 2 ;;
    --host)                HOST="$2"; shift 2 ;;
    --model)               MODEL="$2"; shift 2 ;;
    --tier)                TIER="$2"; shift 2 ;;
    --integrity-method)    INTEGRITY_METHOD="$2"; shift 2 ;;
    --ise)                 ISE_JSON="$2"; shift 2 ;;
    -h|--help)             usage; exit 0 ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

if [ -z "$ARTIFACT" ] || [ -z "$CONTRACT" ] || [ -z "$PERFORMATIVE" ] || [ -z "$OBJECTIVE" ]; then
  echo "Required: --artifact, --contract, --performative, --objective" >&2
  exit 1
fi
if [ ! -r "$ARTIFACT" ]; then
  echo "Cannot read artifact: $ARTIFACT" >&2
  exit 1
fi
if [ ! -r "$CONTRACT" ]; then
  echo "Cannot read contract: $CONTRACT" >&2
  exit 1
fi

# yq invocation tolerant of mikefarah Go yq vs python-yq.
yaml_to_json() {
  if command -v yq >/dev/null 2>&1; then
    if yq eval '.' "$1" -o=json 2>/dev/null; then return 0; fi
    if yq -o=json '.' "$1" 2>/dev/null; then return 0; fi
    if yq '.' "$1" 2>/dev/null; then return 0; fi
  fi
  if command -v python3 >/dev/null 2>&1; then
    python3 -c '
import sys, json, yaml
with open(sys.argv[1]) as f:
  print(json.dumps(yaml.safe_load(f)))
' "$1" 2>/dev/null && return 0
  fi
  return 1
}

CONTRACT_JSON="$(yaml_to_json "$CONTRACT")"
if [ -z "$CONTRACT_JSON" ]; then
  echo "Failed to parse contract YAML: $CONTRACT" >&2
  exit 1
fi

FROM="$(printf '%s' "$CONTRACT_JSON" | jq -r '.from')"
TO="$(printf '%s' "$CONTRACT_JSON" | jq -r '.to')"
EDGE_ORIGIN="$(printf '%s' "$CONTRACT_JSON" | jq -r '.edge_origin')"
if [ -z "$KIND" ]; then
  KIND="$(printf '%s' "$CONTRACT_JSON" | jq -r '.artifacts[0].kind')"
fi
if [ -z "$TOKEN_BUDGET" ]; then
  TOKEN_BUDGET="$(printf '%s' "$CONTRACT_JSON" | jq -r '.context_delta.token_budget_max // 4000')"
fi
if [ -z "$TRUST_LEVEL" ]; then
  TRUST_LEVEL="$(printf '%s' "$CONTRACT_JSON" | jq -r '.trust_level // "standard"')"
fi

# IDs.
new_uuid() {
  if command -v uuidgen >/dev/null 2>&1; then
    uuidgen | tr 'A-Z' 'a-z'
  else
    # Coarse fallback; not a true UUID but conformance only requires uuid-like.
    od -x /dev/urandom | head -1 | awk '{printf("%s%s-%s-%s-%s-%s%s%s\n",$2,$3,$4,$5,$6,$7,$8,$9)}'
  fi
}
[ -z "$MESSAGE_ID" ] && MESSAGE_ID="$(new_uuid)"
[ -z "$THREAD_ID" ]  && THREAD_ID="$MESSAGE_ID"

# Artifact integrity + size.
SIZE_BYTES="$(wc -c < "$ARTIFACT" | tr -d '[:space:]')"
case "$INTEGRITY_METHOD" in
  sha256)
    if command -v shasum >/dev/null 2>&1; then
      INTEGRITY_VALUE="$(shasum -a 256 "$ARTIFACT" | awk '{print $1}')"
    elif command -v sha256sum >/dev/null 2>&1; then
      INTEGRITY_VALUE="$(sha256sum "$ARTIFACT" | awk '{print $1}')"
    else
      echo "shasum/sha256sum unavailable" >&2; exit 2
    fi
    ;;
  hmac-sha256)
    if [ -z "${ECL_HMAC_KEY:-}" ]; then
      echo "ECL_HMAC_KEY required for integrity-method=hmac-sha256" >&2
      exit 1
    fi
    if ! command -v openssl >/dev/null 2>&1; then
      echo "openssl required for integrity-method=hmac-sha256" >&2
      exit 1
    fi
    INTEGRITY_VALUE="$(openssl dgst -sha256 -hmac "$ECL_HMAC_KEY" "$ARTIFACT" | awk '{print $NF}')"
    ;;
  *)
    echo "Unsupported integrity-method: $INTEGRITY_METHOD" >&2
    exit 1
    ;;
esac

# RFC 3339 UTC timestamp.
TS="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# parent_id JSON encoding.
if [ "$PARENT_ID" = "null" ] || [ -z "$PARENT_ID" ]; then
  PARENT_JSON="null"
else
  PARENT_JSON="\"$PARENT_ID\""
fi

# Optional ISE block: validate JSON and prepare argjson arg.
ISE_ARG=""
if [ -n "$ISE_JSON" ]; then
  if ! printf '%s' "$ISE_JSON" | jq -e . >/dev/null 2>&1; then
    echo "--ise value is not valid JSON" >&2; exit 1
  fi
  ISE_ARG="$ISE_JSON"
fi

# Emit envelope. Use jq -n with --arg for safe escaping.
# envelope_version and schema_version default to "2.0" (ECL v2.0 §1.1.1).
# The ise block is inserted when --ise was provided; omitted otherwise
# (ISE is OPTIONAL at v2.0 per §6.5).
if [ -n "$ISE_ARG" ]; then
  jq -n \
    --arg envelope_version "2.0" \
    --arg message_id       "$MESSAGE_ID" \
    --arg thread_id        "$THREAD_ID" \
    --argjson parent_id    "$PARENT_JSON" \
    --arg from_eidolon     "$FROM" \
    --arg from_version     "$FROM_VERSION" \
    --arg to_eidolon       "$TO" \
    --arg to_version       "$TO_VERSION" \
    --arg performative     "$PERFORMATIVE" \
    --arg edge_origin      "$EDGE_ORIGIN" \
    --arg objective        "$OBJECTIVE" \
    --arg artifact_kind    "$KIND" \
    --arg schema_version   "2.0" \
    --arg artifact_path    "$(basename "$ARTIFACT")" \
    --arg sha256           "$INTEGRITY_VALUE" \
    --argjson size_bytes   "$SIZE_BYTES" \
    --argjson token_budget "$TOKEN_BUDGET" \
    --argjson tokens_used  "$TOKENS_USED" \
    --arg summary          "$SUMMARY" \
    --arg trust_level      "$TRUST_LEVEL" \
    --argjson confidence   "$CONFIDENCE" \
    --arg integrity_method "$INTEGRITY_METHOD" \
    --arg integrity_value  "$INTEGRITY_VALUE" \
    --arg ts               "$TS" \
    --arg host             "$HOST" \
    --arg model            "$MODEL" \
    --arg tier             "$TIER" \
    --argjson ise          "$ISE_ARG" \
    '{
      envelope_version: $envelope_version,
      message_id: $message_id,
      thread_id: $thread_id,
      parent_id: $parent_id,
      from: { eidolon: $from_eidolon, version: $from_version },
      to:   { eidolon: $to_eidolon,   version: $to_version },
      performative: $performative,
      edge_origin:  $edge_origin,
      objective:    $objective,
      artifact: {
        kind: $artifact_kind,
        schema_version: $schema_version,
        path: $artifact_path,
        sha256: $sha256,
        size_bytes: $size_bytes
      },
      context_delta: {
        token_budget: $token_budget,
        tokens_used:  $tokens_used,
        input_handles: [],
        summary: $summary
      },
      constraints: { trust_level: $trust_level },
      ise: $ise,
      confidence: $confidence,
      integrity: { method: $integrity_method, value: $integrity_value },
      trace: { ts: $ts, host: $host, model: $model, tier: $tier }
    }'
else
  jq -n \
    --arg envelope_version "2.0" \
    --arg message_id       "$MESSAGE_ID" \
    --arg thread_id        "$THREAD_ID" \
    --argjson parent_id    "$PARENT_JSON" \
    --arg from_eidolon     "$FROM" \
    --arg from_version     "$FROM_VERSION" \
    --arg to_eidolon       "$TO" \
    --arg to_version       "$TO_VERSION" \
    --arg performative     "$PERFORMATIVE" \
    --arg edge_origin      "$EDGE_ORIGIN" \
    --arg objective        "$OBJECTIVE" \
    --arg artifact_kind    "$KIND" \
    --arg schema_version   "2.0" \
    --arg artifact_path    "$(basename "$ARTIFACT")" \
    --arg sha256           "$INTEGRITY_VALUE" \
    --argjson size_bytes   "$SIZE_BYTES" \
    --argjson token_budget "$TOKEN_BUDGET" \
    --argjson tokens_used  "$TOKENS_USED" \
    --arg summary          "$SUMMARY" \
    --arg trust_level      "$TRUST_LEVEL" \
    --argjson confidence   "$CONFIDENCE" \
    --arg integrity_method "$INTEGRITY_METHOD" \
    --arg integrity_value  "$INTEGRITY_VALUE" \
    --arg ts               "$TS" \
    --arg host             "$HOST" \
    --arg model            "$MODEL" \
    --arg tier             "$TIER" \
    '{
      envelope_version: $envelope_version,
      message_id: $message_id,
      thread_id: $thread_id,
      parent_id: $parent_id,
      from: { eidolon: $from_eidolon, version: $from_version },
      to:   { eidolon: $to_eidolon,   version: $to_version },
      performative: $performative,
      edge_origin:  $edge_origin,
      objective:    $objective,
      artifact: {
        kind: $artifact_kind,
        schema_version: $schema_version,
        path: $artifact_path,
        sha256: $sha256,
        size_bytes: $size_bytes
      },
      context_delta: {
        token_budget: $token_budget,
        tokens_used:  $tokens_used,
        input_handles: [],
        summary: $summary
      },
      constraints: { trust_level: $trust_level },
      confidence: $confidence,
      integrity: { method: $integrity_method, value: $integrity_value },
      trace: { ts: $ts, host: $host, model: $model, tier: $tier }
    }'
fi
